export const Category = {
    ITALIAN: 'Category.italian',
    AMERICAN: 'Category.american',
    SPANISH: 'Category.spanish',
    PIZZA: 'Category.pizza',
    STEAKHOUSE: 'Category.steakhouse',
    BAR: 'Category.bar',
    CHINESE: 'Category.chinese',
    VIET_THAI: 'Category.viet_thai',
    BURGERS: 'Category.burgers',
    JAPANESE: 'Category.japanese',
    SUSHI: 'Category.sushi',
    VEGGIE: 'Category.veggie',
    INDIAN: 'Category.indian',
    EMPANADAS: 'Category.empanadas',
    BOULANGERIE: 'Category.boulangerie',
    COFFEE: 'Category.coffee',
    BREWERY: 'Category.brewery',
    PERUVIAN: 'Category.peruvian',
    NIKKEI: 'Category.nikkei',
    ARABIAN: 'Category.arabian',
    MEXICAN: 'Category.mexican',
    GELATO: 'Category.gelato'
}