export class Zone {
  static values: Zone[] = []

  static readonly VEINTEDEJUNIO = new Zone(
    'VEINTEDEJUNIO',
    '20 de Junio'
  )

  static readonly CRUCECITA = new Zone('CRUCECITA', 'Crucecita')
  static readonly ELTALAR = new Zone('ELTALAR', 'El Talar')
  static readonly NUEVEDEABRIL = new Zone('NUEVEDEABRIL', '9 de Abril')
  static readonly ACASSUSO = new Zone('ACASSUSO', 'Acassuso')
  static readonly ADROGUE = new Zone('ADROGUE', 'Adrogué')
  static readonly AGRONOMIA = new Zone('AGRONOMIA', 'Agronomía')
  static readonly ALDOBONZI = new Zone('ALDOBONZI', 'Aldo Bonzi')
  static readonly ALMAGRO = new Zone('ALMAGRO', 'Almagro')
  static readonly AREADEPROMOCIONELTRIANGULO = new Zone(
    'AREADEPROMOCIONELTRIANGULO',
    'Área de Promoción El Triángulo'
  )

  static readonly RINCONDEMILBERG = new Zone('RINCONDEMILBERG', 'Rincón de Milberg')
  static readonly GENERALPACHECO = new Zone('GENERALPACHECO', 'General Pacheco')

  static readonly AVELLANEDA = new Zone('AVELLANEDA', 'Avellaneda')
  static readonly BANFIELD = new Zone('BANFIELD', 'Banfield')
  static readonly BECCAR = new Zone('BECCAR', 'Beccar')
  static readonly BELLA_VISTA = new Zone('BELLA_VISTA', 'Bella Vista')
  static readonly BERAZATEGUI = new Zone('BERAZATEGUI', 'Berazategui')
  static readonly BERISSO = new Zone('BERISSO', 'Berisso')
  static readonly BERNAL = new Zone('BERNAL', 'Bernal')
  static readonly BOSQUES = new Zone('BOSQUES', 'Bosques')
  static readonly BOULOGNE = new Zone('BOULOGNE', 'Boulogne')
  static readonly BURZACO = new Zone('BURZACO', 'Burzaco')
  static readonly CABALLITO = new Zone('CABALLITO', 'Caballito')
  static readonly CANNING = new Zone('CANNING', 'Canning')
  static readonly CASEROS = new Zone('CASEROS', 'Caseros')
  static readonly CASTELAR = new Zone('CASTELAR', 'Castelar')
  static readonly CHILAVERT = new Zone('CHILAVERT', 'Chilavert')
  static readonly CIUDADJARDIN = new Zone('CIUDADJARDIN', 'Ciudad Jardín')
  static readonly CIUDADJARDINPALOMAR = new Zone('CIUDADJARDINPALOMAR', 'Ciudad Jardín Palomar')
  static readonly CIUDADELA = new Zone('CIUDADELA', 'Ciudadela')
  static readonly CONSTITUCION = new Zone('CONSTITUCION', 'Constitución')
  static readonly DEL_VISO = new Zone('DEL_VISO', 'Del Viso')
  static readonly DON_BOSCO = new Zone('DON_BOSCO', 'Don Bosco')
  static readonly EZEIZA = new Zone('EZEIZA', 'Ezeiza')
  static readonly EZPELETA = new Zone('EZPELETA', 'Ezpeleta')
  static readonly FLORENCIO_VARELA = new Zone('FLORENCIO_VARELA', 'Florencio Varela')
  static readonly FLORIDA = new Zone('FLORIDA', 'Florida')
  static readonly GARIN = new Zone('GARIN', 'Garín')
  static readonly GERLI = new Zone('GERLI', 'Gerli')
  static readonly GLEW = new Zone('GLEW', 'Glew')
  static readonly GONZALEZ_CATAN = new Zone('GONZALEZ_CATAN', 'González Catán')
  static readonly GREGORIO_DE_LAFERRERE = new Zone('GREGORIO_DE_LAFERRERE', 'Gregorio de Laferrere')
  static readonly HAEDO = new Zone('HAEDO', 'Haedo')
  static readonly HIPOLITO_YRIGOYEN = new Zone('HIPOLITO_YRIGOYEN', 'Hipólito Yrigoyen')
  static readonly HURLINGHAM = new Zone('HURLINGHAM', 'Hurlingham')
  static readonly ING_PABLO_NOGUES = new Zone('ING_PABLO_NOGUES', 'Ing. Pablo Nogués')
  static readonly ISIDRO_CASANOVA = new Zone('ISIDRO_CASANOVA', 'Isidro Casanova')
  static readonly ITUZAINGO = new Zone('ITUZAINGO', 'Ituzaingó')
  static readonly JOSE_CPAZ = new Zone('JOSE_CPAZ', 'José C. Paz')
  static readonly JOSE_MARMOL = new Zone('JOSE_MARMOL', 'José Mármol')
  static readonly JOSE_LEON_SUAREZ = new Zone('JOSE_LEON_SUAREZ', 'José León Suárez')
  static readonly JUSTO_VILLEGAS = new Zone('JUSTO_VILLEGAS', 'Justo Villegas')
  static readonly LA_TABLADA = new Zone('LA_TABLADA', 'La Tablada')
  static readonly LAFERRERE = new Zone('LAFERRERE', 'Laferrere')
  static readonly LANUS = new Zone('LANUS', 'Lanús')
  static readonly LLAVALLOL = new Zone('LLAVALLOL', 'Llavallol')
  static readonly LOMAS_DE_ZAMORA = new Zone('LOMAS_DE_ZAMORA', 'Lomas de Zamora')
  static readonly LOMAS_DEL_MIRADOR = new Zone('LOMAS_DEL_MIRADOR', 'Lomas del Mirador')
  static readonly LONGCHAMPS = new Zone('LONGCHAMPS', 'Longchamps')
  static readonly LOS_POLVORINES = new Zone('LOS_POLVORINES', 'Los Polvorines')
  static readonly LUJAN = new Zone('LUJAN', 'Luján')
  static readonly MALAVER = new Zone('MALAVER', 'Malaver')
  static readonly MALVINAS_ARGENTINAS = new Zone('MALVINAS_ARGENTINAS', 'Malvinas Argentinas')
  static readonly MANUEL_ALBERTI = new Zone('MANUEL_ALBERTI', 'Manuel Alberti')
  static readonly MANUEL_B_GONNET = new Zone('MANUEL_B_GONNET', 'Manuel B. Gonnet')
  static readonly MARCOS_PAZ = new Zone('MARCOS_PAZ', 'Marcos Paz')
  static readonly MARTINEZ = new Zone('MARTINEZ', 'Martínez')
  static readonly MERLO = new Zone('MERLO', 'Merlo')
  static readonly MIGUELCANELO = new Zone('MIGUELCANELO', 'Miguel Canelo')
  static readonly MINISTRO_RIVADAVIA = new Zone('MINISTRO_RIVADAVIA', 'Ministro Rivadavia')
  static readonly MONTE_CHINGOLO = new Zone('MONTE_CHINGOLO', 'Monte Chingolo')
  static readonly MONTE_GRANDE = new Zone('MONTE_GRANDE', 'Monte Grande')
  static readonly MORENO = new Zone('MORENO', 'Moreno')
  static readonly MORON = new Zone('MORON', 'Morón')
  static readonly MUÑIZ = new Zone('MUÑIZ', 'Muñiz')
  static readonly NUEVAPOMPEYA = new Zone('NUEVAPOMPEYA', 'Nueva Pompeya')
  static readonly NUNEZ = new Zone('NUNEZ', 'Núñez')
  static readonly OLIVOS = new Zone('OLIVOS', 'Olivos')
  static readonly ONCEDESEPTIEMBRE = new Zone('ONCEDESEPTIEMBRE', 'Once de Septiembre')
  static readonly PABLONOGUES = new Zone('PABLONOGUES', 'Pablo Nogués')
  static readonly PABLOPODESTA = new Zone('PABLOPODESTA', 'Pablo Podestá')
  static readonly PALERMO = new Zone('PALERMO', 'Palermo')
  static readonly PARQUEAVELLANEDA = new Zone('PARQUEAVELLANEDA', 'Parque Avellaneda')
  static readonly PARQUECHACABUCO = new Zone('PARQUECHACABUCO', 'Parque Chacabuco')
  static readonly PARQUECHAS = new Zone('PARQUECHAS', 'Parque Chas')
  static readonly PARQUEPATRICIOS = new Zone('PARQUEPATRICIOS', 'Parque Patricios')
  static readonly PARQUESANMARTIN = new Zone('PARQUESANMARTIN', 'Parque San Martín')
  static readonly PASODELREY = new Zone('PASODELREY', 'Paso del Rey')
  static readonly PEREYRA = new Zone('PEREYRA', 'Pereyra')
  static readonly PINEYRO = new Zone('PINEYRO', 'Piñeyro')
  static readonly PLATANOS = new Zone('PLATANOS', 'Plátanos')
  static readonly PONTEVEDRA = new Zone('PONTEVEDRA', 'Pontevedra')
  static readonly PUERTOMADERO = new Zone('PUERTOMADERO', 'Puerto Madero')
  static readonly PALOMAR = new Zone('PALOMAR', 'Palomar')
  static readonly PABLO_PODEROSO = new Zone('PABLO_PODEROSO', 'Pablo Poderoso')
  static readonly PACHECO = new Zone('PACHECO', 'Pacheco')
  static readonly PENAFLOR = new Zone('PENAFLOR', 'Peñaflor')
  static readonly PILAR = new Zone('PILAR', 'Pilar')
  static readonly PINAZO = new Zone('PINAZO', 'Pinazo')
  static readonly POLO_SUR = new Zone('POLO_SUR', 'Polo Sur')
  static readonly PRESIDENTE_DERQUI = new Zone('PRESIDENTE_DERQUI', 'Presidente Derqui')
  static readonly QUILMES = new Zone('QUILMES', 'Quilmes')
  static readonly RAMALLO = new Zone('RAMALLO', 'Ramallo')
  static readonly RAMOS_MEJIA = new Zone('RAMOS_MEJIA', 'Ramos Mejía')
  static readonly RAFAEL_CASTILLO = new Zone('RAFAEL_CASTILLO', 'Rafael Castillo')
  static readonly REMEDIOS_DE_ESCALADA = new Zone('REMEDIOS_DE_ESCALADA', 'Remedios de Escalada')
  static readonly RESIDENCIAL_EL_RIO = new Zone('RESIDENCIAL_EL_RIO', 'Residencial El Río')
  static readonly RICARDO_ROJAS = new Zone('RICARDO_ROJAS', 'Ricardo Rojas')
  static readonly SADOP = new Zone('SADOP', 'SADOP')
  static readonly SAN_ANTONIO_DE_PADUA = new Zone('SAN_ANTONIO_DE_PADUA', 'San Antonio de Padua')
  static readonly SAN_CRISTOBAL = new Zone('SAN_CRISTOBAL', 'San Cristóbal')
  static readonly SAN_FERNANDO = new Zone('SAN_FERNANDO', 'San Fernando')
  static readonly SAN_FRANCISCO_SOLANO = new Zone('SAN_FRANCISCO_SOLANO', 'San Francisco Solano')
  static readonly SAN_ISIDRO = new Zone('SAN_ISIDRO', 'San Isidro')
  static readonly SAN_JOSE = new Zone('SAN_JOSE', 'San José')
  static readonly SAN_JUSTO = new Zone('SAN_JUSTO', 'San Justo')
  static readonly SAN_MARTIN = new Zone('SAN_MARTIN', 'San Martín')
  static readonly SAN_MIGUEL = new Zone('SAN_MIGUEL', 'San Miguel')
  static readonly SAN_PABLO = new Zone('SAN_PABLO', 'San Pablo')
  static readonly SAN_PEDRO = new Zone('SAN_PEDRO', 'San Pedro')
  static readonly SAN_VICENTE = new Zone('SAN_VICENTE', 'San Vicente')
  static readonly SARANDI = new Zone('SARANDI', 'Sarandí')
  static readonly SOLANO = new Zone('SOLANO', 'Solano')
  static readonly TAPIALES = new Zone('TAPIALES', 'Tapiales')
  static readonly TEMPERLEY = new Zone('TEMPERLEY', 'Temperley')
  static readonly TIGRE = new Zone('TIGRE', 'Tigre')
  static readonly TORTUGUITAS = new Zone('TORTUGUITAS', 'Tortuguitas')
  static readonly TRISTAN_SUAREZ = new Zone('TRISTAN_SUAREZ', 'Tristán Suárez')
  static readonly TURDERA = new Zone('TURDERA', 'Turdera')
  static readonly VALENTINALSINA = new Zone('VALENTINALSINA', 'Valentín Alsina')
  static readonly VARELA = new Zone('VARELA', 'Varela')
  static readonly VICTORIA = new Zone('VICTORIA', 'Victoria')
  static readonly VILLA_ADRIANA = new Zone('VILLA_ADRIANA', 'Villa Adriana')
  static readonly VILLA_ALBERTINA = new Zone('VILLA_ALBERTINA', 'Villa Albertina')
  static readonly VILLA_ANGELICA = new Zone('VILLA_ANGELICA', 'Villa Angélica')
  static readonly VILLA_BALLESTER = new Zone('VILLA_BALLESTER', 'Villa Ballester')
  static readonly VILLA_BOSCH = new Zone('VILLA_BOSCH', 'Villa Bosch')
  static readonly VILLA_CARAZA = new Zone('VILLA_CARAZA', 'Villa Caraza')
  static readonly VILLA_CENTENARIO = new Zone('VILLA_CENTENARIO', 'Villa Centenario')
  static readonly VILLA_CLUB = new Zone('VILLA_CLUB', 'Villa Club')
  static readonly VILLA_CRESPO = new Zone('VILLA_CRESPO', 'Villa Crespo')
  static readonly VILLA_DARREGUEIRA = new Zone('VILLA_DARREGUEIRA', 'Villa Darregueira')
  static readonly VILLA_DELMOSQUE = new Zone('VILLA_DELMOSQUE', 'Villa del Mosquito')
  static readonly VILLA_DEL_PARQUE = new Zone('VILLA_DEL_PARQUE', 'Villa del Parque')
  static readonly VILLA_DEL_PLATA = new Zone('VILLA_DEL_PLATA', 'Villa del Plata')
  static readonly VILLA_DELFINA = new Zone('VILLA_DELFINA', 'Villa Delfina')
  static readonly VILLA_DOMINICO = new Zone('VILLA_DOMINICO', 'Villa Dominico')
  static readonly VILLA_EDELMIRA = new Zone('VILLA_EDELMIRA', 'Villa Edelmira')
  static readonly VILLA_EL_CARMEN = new Zone('VILLA_EL_CARMEN', 'Villa El Carmen')
  static readonly VILLA_ELISA = new Zone('VILLA_ELISA', 'Villa Elisa')
  static readonly VILLA_ESPANA = new Zone('VILLA_ESPANA', 'Villa España')
  static readonly VILLA_ESTANZUELA = new Zone('VILLA_ESTANZUELA', 'Villa Estanzuela')
  static readonly VILLA_FIORITO = new Zone('VILLA_FIORITO', 'Villa Fiorito')
  static readonly VILLA_GARIBALDI = new Zone('VILLA_GARIBALDI', 'Villa Garibaldi')
  static readonly VILLA_GODAY_CRUZ = new Zone('VILLA_GODAY_CRUZ', 'Villa Goday Cruz')
  static readonly VILLA_GUILLERMINA = new Zone('VILLA_GUILLERMINA', 'Villa Guillermina')
  static readonly VILLA_INDEPENDENCIA = new Zone('VILLA_INDEPENDENCIA', 'Villa Independencia')
  static readonly VILLA_INSUPERABLE = new Zone('VILLA_INSUPERABLE', 'Villa Insuperable')
  static readonly VILLA_IRIS = new Zone('VILLA_IRIS', 'Villa Iris')
  static readonly VILLA_KRAUSE = new Zone('VILLA_KRAUSE', 'Villa Krause')
  static readonly VILLA_LAFE = new Zone('VILLA_LAFE', 'Villa Laff')
  static readonly VILLA_LINCH = new Zone('VILLA_LINCH', 'Villa Linch')
  static readonly VILLA_LOURDES = new Zone('VILLA_LOURDES', 'Villa Lourdes')
  static readonly VILLA_LUZURIAGA = new Zone('VILLA_LUZURIAGA', 'Villa Luzuriaga')
  static readonly VILLA_MADERO = new Zone('VILLA_MADERO', 'Villa Madero')
  static readonly VILLA_MALDONADO = new Zone('VILLA_MALDONADO', 'Villa Maldonado')
  static readonly VILLA_MARTINEZ = new Zone('VILLA_MARTINEZ', 'Villa Martínez')
  static readonly VILLA_MERCED = new Zone('VILLA_MERCED', 'Villa Merced')
  static readonly VILLA_MONICA = new Zone('VILLA_MONICA', 'Villa Mónica')
  static readonly VILLA_MORRA = new Zone('VILLA_MORRA', 'Villa Morra')
  static readonly VILLA_NUMANCIA = new Zone('VILLA_NUMANCIA', 'Villa Numancia')
  static readonly VILLA_OLGA = new Zone('VILLA_OLGA', 'Villa Olga')
  static readonly VILLA_PARQUE = new Zone('VILLA_PARQUE', 'Villa Parque')
  static readonly VILLA_PIOLIN = new Zone('VILLA_PIOLIN', 'Villa Piolín')
  static readonly VILLA_PROGRESO = new Zone('VILLA_PROGRESO', 'Villa Progreso')
  static readonly VILLA_PUEYRREDON = new Zone('VILLA_PUEYRREDON', 'Villa Pueyrredón')
  static readonly VILLA_RAFFO = new Zone('VILLA_RAFFO', 'Villa Raffo')
  static readonly VILLA_RAMALLO = new Zone('VILLA_RAMALLO', 'Villa Ramallo')
  static readonly VILLA_RAQUEL = new Zone('VILLA_RAQUEL', 'Villa Raquel')
  static readonly VILLA_RICCIARDI = new Zone('VILLA_RICCIARDI', 'Villa Ricciardi')
  static readonly VILLA_ROBERTO = new Zone('VILLA_ROBERTO', 'Villa Roberto')
  static readonly VILLA_RODOLFO = new Zone('VILLA_RODOLFO', 'Villa Rodolfo')
  static readonly VILLA_ROSA = new Zone('VILLA_ROSA', 'Villa Rosa')
  static readonly VILLA_SANTOS_TESEI = new Zone('VILLA_SANTOS_TESEI', 'Villa Santos Tesei')
  static readonly VILLA_SARMIENTO = new Zone('VILLA_SARMIENTO', 'Villa Sarmiento')
  static readonly VILLA_SOCORRO = new Zone('VILLA_SOCORRO', 'Villa Socorro')
  static readonly VILLA_TESEI = new Zone('VILLA_TESEI', 'Villa Tesei')
  static readonly VILLA_TITA = new Zone('VILLA_TITA', 'Villa Tita')
  static readonly VILLA_TRANQUILA = new Zone('VILLA_TRANQUILA', 'Villa Tranquila')
  static readonly VILLA_TRIANGULO = new Zone('VILLA_TRIANGULO', 'Villa Triángulo')
  static readonly VILLA_VENTANA = new Zone('VILLA_VENTANA', 'Villa Ventana')
  static readonly VILLA_VICTORIA = new Zone('VILLA_VICTORIA', 'Villa Victoria')
  static readonly VILLA_VIOR = new Zone('VILLA_VIOR', 'Villa Vior')
  static readonly VILLA_WALDEMAR = new Zone('VILLA_WALDEMAR', 'Villa Waldemar')
  static readonly VILLA_ZAGALA = new Zone('VILLA_ZAGALA', 'Villa Zagala')
  static readonly VILLA_ZAPIOLA = new Zone('VILLA_ZAPIOLA', 'Villa Zapiola')
  static readonly VILLA_ZUMAQUE = new Zone('VILLA_ZUMAQUE', 'Villa Zumaque')

  private constructor (
    public readonly name: string,
    public readonly description: string
  ) {
    Zone.values.push(this)
  }

  static fromName (name: string): Zone | undefined {
    return Zone.values.find((zone) => zone.name === name)
  }

  static fromDescription (description: string): Zone | undefined {
    return Zone.values.find((zone) => zone.description === description)
  }
}
