package ar.edu.itba.paw.model;

public enum Zone {
    VEINTEDEJUNIO("20 de Junio"),
    NUEVEDEABRIL("9 de Abril"),
    ACASSUSO("Acassuso"),
    ADROGUE("Adrogué"),
    AGRONOMIA("Agronomía"),
    ALDOBONZI("Aldo Bonzi"),
    ALMAGRO("Almagro"),
    AREADEPROMOCIONELTRIANGULO("Área de Promoción El Triángulo"),
    AVELLANEDA("Avellaneda"),
    BALVANERA("Balvanera"),
    BANFIELD("Banfield"),
    BARRACAS("Barracas"),
    BECCAR("Beccar"),
    BELGRANO("Belgrano"),
    BELLAVISTA("Bella Vista"),
    BENAVIDEZ("Benavídez"),
    BERAZATEGUI("Berazategui"),
    BERAZATEGUIOESTE("Berazategui Oeste"),
    BERNAL("Bernal"),
    BERNALOESTE("Bernal Oeste"),
    BILLINGHURST("Billinghurst"),
    BOEDO("Boedo"),
    BOSQUES("Bosques"),
    BOULOGNE("Boulogne"),
    BURZACO("Burzaco"),
    CABALLITO("Caballito"),
    CAMPODEMAYO("Campo de Mayo"),
    CANNINGE("Canning (Esteban Echeverría)"),
    CANNINGEE("Canning (Ezeiza)"),
    CARAPACHAY("Carapachay"),
    CARLOSSPEGAZZINI("Carlos Spegazzini"),
    CASEROS("Caseros"),
    CASTELAR("Castelar"),
    CHACARITA("Chacarita"),
    CHURRUCA("Churruca"),
    CIUDADEVITA("Ciudad Evita"),
    CIUDADJARDINLOMASDELPALOMAR("Ciudad Jardín Lomas del Palomar"),
    CIUDADELA("Ciudadela"),
    CLAYPOLE("Claypole"),
    COGHLAN("Coghlan"),
    COLEGIALES("Colegiales"),
    CONSTITUCION("Constitución"),
    CRUCECITA("Crucecita"),
    CUARTELV("Cuartel V"),
    DELVISO("Del Viso"),
    DIQUELUJAN("Dique Luján"),
    DOCKSUD("Dock Sud"),
    DONBOSCO("Don Bosco"),
    DONORIONE("Don Orione"),
    DONTORCUATO("Don Torcuato"),
    ELJAGUEL("El Jagüel"),
    ELLIBERTADOR("El Libertador"),
    ELPALOMAR("El Palomar"),
    ELPATO("El Pato"),
    ELTALAR("El Talar"),
    ESTEBANECHEVERRIA("Esteban Echeverría"),
    EZPELETA("Ezpeleta"),
    EZPELETAOESTE("Ezpeleta Oeste"),
    FLORENCIOVARELA("Florencio Varela"),
    FLORES("Flores"),
    FLORESTA("Floresta"),
    FLORIDA("Florida"),
    FLORIDAOESTE("Florida Oeste"),
    FRANCISCOALVAREZ("Francisco Álvarez"),
    GENERALPACHECO("General Pacheco"),
    GERLIA("Gerli (Avellaneda)"),
    GERLIL("Gerli (Lanús)"),
    GLEW("Glew"),
    GOBERNADORCOSTA("Gobernador Costa"),
    GONZALEZCATAN("González Catán"),
    GRANDBOURG("Grand Bourg"),
    GREGORIODELAFERRERE("Gregorio de Laferrere"),
    GUILLERMOHUDSON("Guillermo Hudson"),
    HAEDO("Haedo"),
    HURLINGHAM("Hurlingham"),
    INGENIEROADOLFOSOURDEAUX("Ingeniero Adolfo Sourdeaux"),
    INGENIEROALLAN("Ingeniero Allan"),
    INGENIEROBUDGE("Ingeniero Budge"),
    ISIDROCASANOVA("Isidro Casanova"),
    ITUZAINGO("Ituzaingó"),
    JOSECPAZ("José C. Paz"),
    JOSEINGENIEROS("José Ingenieros"),
    JOSELEONSUAREZ("José León Suárez"),
    JOSEMARIAEZEIZA("José María Ezeiza"),
    JOSEMARMOL("José Mármol"),
    JUANMARIAGUTIERREZ("Juan María Gutiérrez"),
    LABOCA("La Boca"),
    LACAPILLA("La Capilla"),
    LALUCILA("La Lucila"),
    LAPATERNAL("La Paternal"),
    LAREJA("La Reja"),
    LATABLADA("La Tablada"),
    LAUNION("La Unión"),
    LANUS("Lanús"),
    LANUSOESTE("Lanús Oeste"),
    LIBERTAD("Libertad"),
    LINIERS("Liniers"),
    LLAVALLOL("Llavallol"),
    LOMAHERMOSA3("Loma Hermosa (3 de Febrero)"),
    LOMAHERMOSASM("Loma Hermosa (San Martín)"),
    LOMAHERMOSA("Loma Hermosa"),
    LOMASDEZAMORA("Lomas de Zamora"),
    LOMASDELMIRADOR("Lomas del Mirador"),
    LONGCHAMPS("Longchamps"),
    LOSPOLVORINES("Los Polvorines"),
    LUISGUILLON("Luis Guillón"),
    MALVINASARGENTINAS("Malvinas Argentinas"),
    MARIANOACOSTA("Mariano Acosta"),
    MARTINCORONADO("Martín Coronado"),
    MARTINEZ("Martínez"),
    MATADEROS("Mataderos"),
    MERLO("Merlo"),
    MINISTRORIVADAVIA("Ministro Rivadavia"),
    MONSERRAT("Monserrat"),
    MONTECASTRO("Monte Castro"),
    MONTECHINGOLO("Monte Chingolo"),
    MONTEGRANDE("Monte Grande"),
    MORENO("Moreno"),
    MORON("Morón"),
    MUNRO("Munro"),
    MUNIZ("Muñiz"),
    NUEVAPOMPEYA("Nueva Pompeya"),
    NUNEZ("Núñez"),
    OLIVOS("Olivos"),
    ONCEDESEPTIEMBRE("Once de Septiembre"),
    PABLONOGUES("Pablo Nogués"),
    PABLOPODESTA("Pablo Podestá"),
    PALERMO("Palermo"),
    PARQUEAVELLANEDA("Parque Avellaneda"),
    PARQUECHACABUCO("Parque Chacabuco"),
    PARQUECHAS("Parque Chas"),
    PARQUEPATRICIOS("Parque Patricios"),
    PARQUESANMARTIN("Parque San Martín"),
    PASODELREY("Paso del Rey"),
    PEREYRA("Pereyra"),
    PINEYRO("Piñeyro"),
    PLATANOS("Plátanos"),
    PONTEVEDRA("Pontevedra"),
    PUERTOMADERO("Puerto Madero"),
    QUILMES("Quilmes"),
    QUILMESOESTE("Quilmes Oeste"),
    RAFAELCALZADA("Rafael Calzada"),
    RAFAELCASTILLO("Rafael Castillo"),
    RAMOSMEJIA("Ramos Mejía"),
    RANELAGH("Ranelagh"),
    RECOLETA("Recoleta"),
    REMEDIOSDEESCALADA3("Remedios de Escalada (3 de Febrero)"),
    REMEDIOSDEESCALADAL("Remedios de Escalada (Lanús)"),
    RETIRO("Retiro"),
    RICARDOROJAS("Ricardo Rojas"),
    RINCONDEMILBERG("Rincón de Milberg"),
    SAAVEDRA("Saavedra"),
    SAENZPENA("Sáenz Peña"),
    SANANDRES("San Andrés"),
    SANANTONIODEPADUA("San Antonio de Padua"),
    SANCRISTOBAL("San Cristóbal"),
    SANFERNANDO("San Fernando"),
    SANFRANCISCOSOLANOQ("San Francisco Solano (Quilmes)"),
    SANFRANCISCOSOLANOAB("San Francisco Solano (Alte. Brown)"),
    SANISIDRO("San Isidro"),
    SANJOSE("San José"),
    SANJUSTO("San Justo"),
    SANMARTIN("San Martín"),
    SANMIGUEL("San Miguel"),
    SANNICOLAS("San Nicolás"),
    SANTELMO("San Telmo"),
    SANTAROSA("Santa Rosa"),
    SANTOSLUGARES("Santos Lugares"),
    SARANDI("Sarandí"),
    SOURIGUES("Sourigues"),
    TAPIALES("Tapiales"),
    TEMPERLEY("Temperley"),
    TIGRE("Tigre"),
    TORTUGUITASM("Tortuguitas (Malvinas)"),
    TORTUGUITASJ("Tortuguitas (José C. Paz)"),
    TRISTANSUAREZ("Tristán Suárez"),
    TRONCOSDELTALAR("Troncos del Talar"),
    TRUJUI("Trujui"),
    TURDERA("Turdera"),
    UDAONDO("Udaondo"),
    VALENTINALSINA("Valentín Alsina"),
    VELEZSARSFIELD("Vélez Sársfield"),
    VERSALLES("Versalles"),
    VICENTELOPEZ("Vicente López"),
    VICTORIA("Victoria"),
    VILLAADELINAVL("Villa Adelina (Vte López)"),
    VILLAADELINASI("Villa Adelina (San Isidro)"),
    VILLABALLESTER("Villa Ballester"),
    VILLABOSCH("Villa Bosch"),
    VILLABROWN("Villa Brown"),
    VILLACENTENARIO("Villa Centenario"),
    VILLACRESPO("Villa Crespo"),
    VILLADEMAYO("Villa de Mayo"),
    VILLADELPARQUE("Villa del Parque"),
    VILLADEVOTO("Villa Devoto"),
    VILLADOMINICO("Villa Domínico"),
    VILLAESPANA("Villa España"),
    VILLAFIORITO("Villa Fiorito"),
    VILLAGENERALMITRE("Villa General Mitre"),
    VILLALAFLORIDA("Villa La Florida"),
    VILLALUGANO("Villa Lugano"),
    VILLALURO("Villa Luro"),
    VILLALUZURIAGA("Villa Luzuriaga"),
    VILLALYNCH("Villa Lynch"),
    VILLAMADERO("Villa Madero"),
    VILLAMAIPU("Villa Maipú"),
    VILLAMARTELLI("Villa Martelli"),
    VILLAORTUZAR("Villa Ortúzar"),
    VILLAPUEYRREDON("Villa Pueyrredón"),
    VILLARAFFO("Villa Raffo"),
    VILLAREAL("Villa Real"),
    VILLARIACHUELO("Villa Riachuelo"),
    VILLASANLUIS("Villa San Luis"),
    VILLASANTARITA("Villa Santa Rita"),
    VILLASARMIENTO("Villa Sarmiento"),
    VILLASOLDATI("Villa Soldati"),
    VILLATESEI("Villa Tesei"),
    VILLAURQUIZA("Villa Urquiza"),
    VILLAVATTEONE("Villa Vatteone"),
    VIRREYDELPINO("Virrey del Pino"),
    VIRREYES("Virreyes"),
    WILDE("Wilde"),
    WILLIAMCMORRIS("William C. Morris");

    private final String name;

    Zone(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public long getId() {
        return ordinal();
    }

    public static Zone getByOrdinal(long ordinal) {
        for (Zone zone : Zone.values()) {
            if (zone.ordinal() == ordinal) {
                return zone;
            }
        }
        return null;
    }
}
