package ar.edu.itba.paw.model;

public enum Zone {
    VEINTEDEJUNIO("20 de Junio"),
    NUEVEDEABRIL("9 de Abril"),
    ACASSUSO("Acassuso"),
    ADROGUE("Adrogue"),
    AGRONOMIA("Agronomia"),
    ALDOBONZI("Aldo Bonzi"),
    ALMAGRO("Almagro"),
    AREADEPROMOCIONELTRIANGULO("Area de Promocion El Triangulo"),
    AVELLANEDA("Avellaneda"),
    BALVANERA("Balvanera"),
    BANFIELD("Banfield"),
    BARRACAS("Barracas"),
    BECCAR("Beccar"),
    BELGRANO("Belgrano"),
    BELLAVISTA("Bella Vista"),
    BENAVIDEZ("Benavidez"),
    BERAZATEGUI("Berazategui"),
    BERAZATEGUIOESTE("Berazategui Oeste"),
    BERNAL("Bernal"),
    BERNALOESTE("Bernal Oeste"),
    BILLINGHURST("Billinghurst"),
    BOEDO("Boedo"),
    BOSQUES("Bosques"),
    BOULOGNE("Boulogne"),
    BURZACO("Burzaco"),
    CABALLITO("Caballito"),
    CAMPODEMAYO("Campo de Mayo"),
    CANNINGE("Canning (Esteban Echeverria)"),
    CANNINGEE("Canning (Ezeiza)"),
    CARAPACHAY("Carapachay"),
    CARLOSSPEGAZZINI("Carlos Spegazzini"),
    CASEROS("Caseros"),
    CASTELAR("Castelar"),
    CHACARITA("Chacarita"),
    CHURRUCA("Churruca"),
    CIUDADEVITA("Ciudad Evita"),
    CIUDADJARDINLOMASDELPALOMAR("Ciudad Jardin Lomas del Palomar"),
    CIUDADELA("Ciudadela"),
    CLAYPOLE("Claypole"),
    COGHLAN("Coghlan"),
    COLEGIALES("Colegiales"),
    CONSTITUCION("Constitucion"),
    CRUCECITA("Crucecita"),
    CUARTELV("Cuartel V"),
    DELVISO("Del Viso"),
    DIQUELUJAN("Dique Lujan"),
    DOCKSUD("Dock Sud"),
    DONBOSCO("Don Bosco"),
    DONORIONE("Don Orione"),
    DONTORCUATO("Don Torcuato"),
    ELJAGUEL("El Jagüel"),
    ELLIBERTADOR("El Libertador"),
    ELPALOMAR("El Palomar"),
    ELPATO("El Pato"),
    ELTALAR("El Talar"),
    ESTEBANECHEVERRIA("Esteban Echeverria"),
    EZPELETA("Ezpeleta"),
    EZPELETAOESTE("Ezpeleta Oeste"),
    FLORENCIOVARELA("Florencio Varela"),
    FLORES("Flores"),
    FLORESTA("Floresta"),
    FLORIDA("Florida"),
    FLORIDAOESTE("Florida Oeste"),
    FRANCISCOALVAREZ("Francisco Alvarez"),
    GENERALPACHECO("General Pacheco"),
    GERLIA("Gerli (Avellaneda)"),
    GERLIL("Gerli (Lanus)"),
    GLEW("Glew"),
    GOBERNADORCOSTA("Gobernador Costa"),
    GONZALEZCATAN("Gonzalez Catan"),
    GRANDBOURG("Grand Bourg"),
    GREGORIODELAFERRERE("Gregorio de Laferrere"),
    GUILLERMOHUDSON("Guillermo Hudson"),
    HAEDO("Haedo"),
    HURLINGHAM("Hurlingham"),
    INGENIEROADOLFOSOURDEAUX("Ingeniero Adolfo Sourdeaux"),
    INGENIEROALLAN("Ingeniero Allan"),
    INGENIEROBUDGE("Ingeniero Budge"),
    ISIDROCASANOVA("Isidro Casanova"),
    ITUZAINGO("Ituzaingo"),
    JOSECPAZ("Jose C. Paz"),
    JOSEINGENIEROS("Jose Ingenieros"),
    JOSELEONSUAREZ("Jose Leon Suarez"),
    JOSEMARIAEZEIZA("Jose Maria Ezeiza"),
    JOSEMARMOL("Jose Marmol"),
    JUANMARIAGUTIERREZ("Juan Maria Gutierrez"),
    LABOCA("La Boca"),
    LACAPILLA("La Capilla"),
    LALUCILA("La Lucila"),
    LAPATERNAL("La Paternal"),
    LAREJA("La Reja"),
    LATABLADA("La Tablada"),
    LAUNION("La Union"),
    LANUS("Lanus"),
    LANUSOESTE("Lanus Oeste"),
    LIBERTAD("Libertad"),
    LINIERS("Liniers"),
    LLAVALLOL("Llavallol"),
    LOMAHERMOSA3("Loma Hermosa (3 de Febrero)"),
    LOMAHERMOSASM("Loma Hermosa (San Martin)"),
    LOMAHERMOSA("Loma Hermosa"),
    LOMASDEZAMORA("Lomas de Zamora"),
    LOMASDELMIRADOR("Lomas del Mirador"),
    LONGCHAMPS("Longchamps"),
    LOSPOLVORINES("Los Polvorines"),
    LUISGUILLON("Luis Guillon"),
    MALVINASARGENTINAS("Malvinas Argentinas"),
    MARIANOACOSTA("Mariano Acosta"),
    MARTINCORONADO("Martin Coronado"),
    MARTINEZ("Martinez"),
    MATADEROS("Mataderos"),
    MERLO("Merlo"),
    MINISTRORIVADAVIA("Ministro Rivadavia"),
    MONSERRAT("Monserrat"),
    MONTECASTRO("Monte Castro"),
    MONTECHINGOLO("Monte Chingolo"),
    MONTEGRANDE("Monte Grande"),
    MORENO("Moreno"),
    MORON("Moron"),
    MUNRO("Munro"),
    MUNIZ("Muñiz"),
    NUEVAPOMPEYA("Nueva Pompeya"),
    NUNEZ("Nuñez"),
    OLIVOS("Olivos"),
    ONCEDESEPTIEMBRE("Once de Septiembre"),
    PABLONOGUES("Pablo Nogues"),
    PABLOPODESTA("Pablo Podesta"),
    PALERMO("Palermo"),
    PARQUEAVELLANEDA("Parque Avellaneda"),
    PARQUECHACABUCO("Parque Chacabuco"),
    PARQUECHAS("Parque Chas"),
    PARQUEPATRICIOS("Parque Patricios"),
    PARQUESANMARTIN("Parque San Martin"),
    PASODELREY("Paso del Rey"),
    PEREYRA("Pereyra"),
    PINEYRO("Piñeyro"),
    PLATANOS("Platanos"),
    PONTEVEDRA("Pontevedra"),
    PUERTOMADERO("Puerto Madero"),
    QUILMES("Quilmes"),
    QUILMESOESTE("Quilmes Oeste"),
    RAFAELCALZADA("Rafael Calzada"),
    RAFAELCASTILLO("Rafael Castillo"),
    RAMOSMEJIA("Ramos Mejia"),
    RANELAGH("Ranelagh"),
    RECOLETA("Recoleta"),
    REMEDIOSDEESCALADA3("Remedios de Escalada (3 de Febrero)"),
    REMEDIOSDEESCALADAL("Remedios de Escalada (Lanus)"),
    RETIRO("Retiro"),
    RICARDOROJAS("Ricardo Rojas"),
    RINCONDEMILBERG("Rincon de Milberg"),
    SAAVEDRA("Saavedra"),
    SAENZPENA("Saenz Peña"),
    SANANDRES("San Andres"),
    SANANTONIODEPADUA("San Antonio de Padua"),
    SANCRISTOBAL("San Cristobal"),
    SANFERNANDO("San Fernando"),
    SANFRANCISCOSOLANOQ("San Francisco Solano (Quilmes)"),
    SANFRANCISCOSOLANOAB("San Francisco Solano (Alte. Brown)"),
    SANISIDRO("San Isidro"),
    SANJOSE("San Jose"),
    SANJUSTO("San Justo"),
    SANMARTIN("San Martin"),
    SANMIGUEL("San Miguel"),
    SANNICOLAS("San Nicolas"),
    SANTELMO("San Telmo"),
    SANTAROSA("Santa Rosa"),
    SANTOSLUGARES("Santos Lugares"),
    SARANDI("Sarandi"),
    SOURIGUES("Sourigues"),
    TAPIALES("Tapiales"),
    TEMPERLEY("Temperley"),
    TIGRE("Tigre"),
    TORTUGUITASM("Tortuguitas (Malvinas)"),
    TORTUGUITASJ("Tortuguitas (Jose C. Paz)"),
    TRISTANSUAREZ("Tristan Suarez"),
    TRONCOSDELTALAR("Troncos del Talar"),
    TRUJUI("Trujui"),
    TURDERA("Turdera"),
    UDAONDO("Udaondo"),
    VALENTINALSINA("Valentin Alsina"),
    VELEZSARSFIELD("Velez Sarsfield"),
    VERSALLES("Versalles"),
    VICENTELOPEZ("Vicente Lopez"),
    VICTORIA("Victoria"),
    VILLAADELINAVL("Villa Adelina (Vte Lopez)"),
    VILLAADELINASI("Villa Adelina (San Isidro)"),
    VILLABALLESTER("Villa Ballester"),
    VILLABOSCH("Villa Bosch"),
    VILLABROWN("Villa Brown"),
    VILLACENTENARIO("Villa Centenario"),
    VILLACRESPO("Villa Crespo"),
    VILLADEMAYO("Villa de Mayo"),
    VILLADELPARQUE("Villa del Parque"),
    VILLADEVOTO("Villa Devoto"),
    VILLADOMINICO("Villa Dominico"),
    VILLAESPANA("Villa España"),
    VILLAFIORITO("Villa Fiorito"),
    VILLAGENERALMITRE("Villa General Mitre"),
    VILLALAFLORIDA("Villa La Florida"),
    VILLALUGANO("Villa Lugano"),
    VILLALURO("Villa Luro"),
    VILLALUZURIAGA("Villa Luzuriaga"),
    VILLALYNCH("Villa Lynch"),
    VILLAMADERO("Villa Madero"),
    VILLAMAIPU("Villa Maipu"),
    VILLAMARTELLI("Villa Martelli"),
    VILLAORTUZAR("Villa Ortuzar"),
    VILLAPUEYRREDON("Villa Pueyrredon"),
    VILLARAFFO("Villa Raffo"),
    VILLAREAL("Villa Real"),
    VILLARIACHUELO("Villa Riachuelo"),
    VILLASANLUIS("Villa San Luis"),
    VILLASANTARITA("Villa Santa Rita"),
    VILLASARMIENTO("Villa Sarmiento"),
    VILLASOLDATI("Villa Soldati"),
    VILLATESEI("Villa Tesei"),
    VILLAURQUIZA("Villa Urquiza"),
    VILLAVATTEONE("Villa Vatteone"),
    VIRREYDELPINO("Virrey del Pino"),
    VIRREYES("Virreyes"),
    WILDE("Wilde"),
    WILLIAMCMORRIS("William C. Morris");

    private final String name;

    Zone(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public long getId() {
        return ordinal();
    }

    public static Zone getByOrdinal(long ordinal) {
        for (Zone zone : Zone.values()) {
            if (zone.ordinal() == ordinal) {
                return zone;
            }
        }
        return null;
    }

    public static Zone getByName(String name) {
        for (Zone zone : Zone.values()) {
            if (zone.getName().equals(name)) {
                return zone;
            }
        }
        return null;
    }
}
